# a=int(input("Enter your age: "))

# if(a>=18):
#     print("you are above the age of concent")
#     print("Good for you")

# else:
#     print("You are below the ahe of concent")   





# a=int(input("Enter your age: "))
# if(a%2 == 0):
#     print("a is even")
# if(a>=18):
#     print("you are above the age of concent")
#     print("Good for you")

# else:
#     print("You are below the ahe of concent")   


# '''''''''
# int= i=1
# while(i<6):
#     print(i)
#     i+=1

